export const SET_VIDEOS = "SET_VIDEOS";
export const SET_VIDEOS_LOADING = "SET_VIDEOS_LOADING";
export const SET_POPULAR_VIDEOS = "SET_POPULAR_VIDEOS";
export const SET_NEXT_PAGE_TOKEN = "SET_NEXT_PAGE_TOKEN";
export const SET_PREV_PAGE_TOKEN = "SET_PREV_PAGE_TOKEN";
